spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
    alicloud:
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
      access-key: LTAI5tScF2h4wstSGTYYAzzv
      secret-key: gBgu6nrBTuElKddBIAPe9aadz2DRdv
  application:
    name: cubemall-third-party
server:
  port: 30000